-- Create the 'purchases' table
CREATE TABLE public.purchases (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  email text NULL,
  password text NULL,
  amount integer NULL,
  CONSTRAINT purchases_pkey PRIMARY KEY (id)
);

-- Optional: Enable Row Level Security (RLS) for the table
-- It's a good practice for security in Supabase.
-- This policy allows public anonymous access to insert rows.
-- You might want to adjust this based on your security needs.
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for anonymous users" ON public.purchases
AS PERMISSIVE FOR INSERT
TO anon
WITH CHECK (true);
